/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei';
import { Mesh, MeshStandardMaterial } from 'three';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
    nodes: {
        bottomBun: Mesh;
        meat: Mesh;
        cheese: Mesh;
        topBun: Mesh;
    };
    materials: {
        BunMaterial: MeshStandardMaterial;
        SteakMaterial: MeshStandardMaterial;
        CheeseMaterial: MeshStandardMaterial;
    };
};

export function TestJSXModel({
    topBunScale = 1,
    ...props
}: JSX.IntrinsicElements['group'] & { topBunScale?: number }) {
    const { nodes, materials } = useGLTF(
        '/Hamburger/Hamburger.glb'
    ) as GLTFResult;
    return (
        <group {...props} dispose={null}>
            <mesh
                name="bottomBun"
                castShadow
                receiveShadow
                geometry={nodes.bottomBun.geometry}
                material={materials.BunMaterial}
            />
            <mesh
                name="meat"
                castShadow
                receiveShadow
                geometry={nodes.meat.geometry}
                material={materials.SteakMaterial}
                position={[0, 2.8, 0]}
            />
            <mesh
                name="cheese"
                castShadow
                receiveShadow
                geometry={nodes.cheese.geometry}
                material={materials.CheeseMaterial}
                position={[0, 3, 0]}
            />
            <mesh
                name="topBun"
                castShadow
                receiveShadow
                geometry={nodes.topBun.geometry}
                material={materials.BunMaterial}
                position={[0, 1.8, 0]}
                scale={topBunScale}
            />
        </group>
    );
}

useGLTF.preload('/Hamburger/Hamburger.glb');
